name: Undefined
favicon: null
layout_spectrum: 0.62452
typography_spectrum: 0.69015
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#720006'
    - '#0b214e'
    - '#fefefe'
    - '#3094ab'
  brandStrength: 0.25
  lightness: 0.875
  saturation: 0.10975258448161185
  rhythmicContrast: 0.25
purpose: []
